import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ProviderRedux from "./providerRedux"
import "./globals.css";
import Header from "./(components)/navbar/header";
import "./page.modal.scss"
import "./styles/modals.scss"
import UpDateData from "./hooks/hooks";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Apple",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> 
      <ProviderRedux>
      <UpDateData/>

        <Header/>
          <section id="global">
           {children}
          </section>
      </ProviderRedux>
      </body>
    </html>
  );
}
